.github/workflows/publish.yml
fixes publish action with `apt-get update`
=> fix(ci): fix publish action

.github/workflows/publish.yml, CONTRIBUTING.md, RELEASE_PROCESS.md
Aligning vigilante repo with babylon dev process
=> chore(*): switch to trunk based dev

btcclient/client_wallet.go, config/config.go
=> chore(*): minor cleanup

btcstaking-tracker/btcslasher/bootstrapping_test.go, btcstaking-tracker/btcslasher/slasher_test.go, monitor/btcscanner/btc_scanner_test.go, monitor/liveness_checker_test.go, monitor/query_test.go, reporter/utils_test.go, retrywrap/retry_test.go, submitter/poller/poller_test.go, submitter/relayer/change_address_test.go, types/btccache_test.go, types/ckpt_cache_test.go, types/ckpt_segment_test.go, types/indexed_block_test.go
=> chore(*): parallel tests

e2etest/container/config.go, e2etest/container/container.go, e2etest/test_manager.go, testutil/version.go
Parse go mod file in order to get docker image version in e2e tests
=> chore(e2e): parse go mod file

config/dbconfig.go, sample-vigilante-docker.yml, sample-vigilante.yml
- Fix db config mapping for `autocompactminage` and `dbtimeout`
- Add dbconfig to samples
=> fix: db config

btcstaking-tracker/btcslasher/slasher_test.go, e2etest/test_manager_btcstaking.go, go.mod, go.sum
- upgrade babylond to `v0.11.0`
- e2e amend
=> chore(*): upgrade babylond to `v0.11.0`

CHANGELOG.md
=> chore(changelog): backport changelog

CHANGELOG.md
=> chore(ch): backport changelog

CHANGELOG.md, go.mod, go.sum
Upgades bbn dependancy to v0.15.0
=> chore(gomod): upgrade babylon to v0.15.0

CHANGELOG.md
=> chore(*): update changelog

CHANGELOG.md
=> chore(*): update changelog (#91)

.github/workflows/goreleaser.yml
gorelaser write permissions for releaser
=> chore(.github): write permissions

CHANGELOG.md
=> chore(*): changelog update

CHANGELOG.md
=> chore(*): changelog update (#103)

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/expected_babylon_client.go, btcstaking-tracker/stakingeventwatcher/mock_babylon_client.go, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, btcstaking-tracker/tracker.go, e2etest/unbondingwatcher_e2e_test.go
Wait for the stacking transaction to be k-deep before submitting the inclusion proof
=> fix(swe): wait for stacking tx to be k-deep (#106)

CHANGELOG.md
=> backport: update changelog (#109)

CHANGELOG.md
=> chore(*): update changelog v0.17.0

CHANGELOG.md
=> chore(*): update changelog v0.17.0 (#112)

CHANGELOG.md, go.mod, go.sum
=> chore(*): bump bbn to v0.17.1 (#115)

CHANGELOG.md
=> chore: backport update changelog (#118)

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, metrics/btcstaking_tracker.go
Adds more metrics for better visibility
=> chore(bstracker): add more metrics

CHANGELOG.md
=> chore: update changelog (#125)

CHANGELOG.md, e2etest/test_manager_btcstaking.go, go.mod, go.sum
=> chore: bump babylon to v0.18.0

CHANGELOG.md, go.mod, go.sum
=> chore: bump babylon v1.0.0-rc.1

CHANGELOG.md, config/grpc.go, config/grpcweb.go, submitter/relayer/relayer.go
=> fix: resend tx panic

CHANGELOG.md, submitter/relayer/relayer.go
We forgot to update the time o the checkpoint.
closes #151 again
=> fix: resubmit interval

CHANGELOG.md
=> chore: update changelog v0.19.2 (#164) [backport]

CHANGELOG.md, btcclient/client_wallet.go, btcclient/interface.go, submitter/relayer/relayer.go, testutil/mocks/btcclient.go
=> chore: refactor checkpoint tx submission

CHANGELOG.md, btcclient/client_wallet.go, btcclient/interface.go, submitter/relayer/relayer.go, testutil/mocks/btcclient.go
=> chore: refactor checkpoint tx submission (#166) [backport]

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, btcstaking-tracker/stakingeventwatcher/tracked_delegations.go
=> fix: delegation iter (#171) [backport]

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher_test.go, btcstaking-tracker/stakingeventwatcher/tracked_delegations.go, metrics/btcstaking_tracker.go
=> backport: metrics

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, btcstaking-tracker/stakingeventwatcher/tracked_delegations.go, e2etest/unbondingwatcher_e2e_test.go
We were returning nil, making the statement never true
=> fix: removing from metrics tracker (#184)

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher_test.go, metrics/btcstaking_tracker.go
Adds new metric for tracker, less log noise
=> chore: adds more metrics

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher_test.go, metrics/btcstaking_tracker.go
Adds new metric for tracker, less log noise
=> chore: adds more metrics (#190)

CHANGELOG.md, e2etest/bitcoind_node_setup.go, e2etest/container/config.go, e2etest/container/container.go, e2etest/electrs_setup.go, e2etest/test_manager.go
Keeping PRs small, this one just adds indexer container which is connected to the bitcoind node
=> feat: add indexer in e2e

CHANGELOG.md, config/btcstaking_tracker.go
=> chore: bigger batch size for fetching delegations

README.md, sample-vigilante.yml
Updates readme and sample config
=> chore: sample config

CHANGELOG.md, submitter/relayer/relayer.go
=> fix: reselect inputs after adding manual output

CHANGELOG.md, submitter/relayer/relayer.go
=> fix: consider minimal fee for bump

CHANGELOG.md, monitor/btcscanner/btc_scanner.go, reporter/reporter.go, types/ckpt_cache.go, types/ckpt_cache_test.go, types/ckpt_segment.go
Periodically clean up unmatched checkpoints. **BP2-014**
closes #215
=> chore: cleanup unmatched checkpoints

CHANGELOG.md, btcclient/client_wallet.go, config/bitcoin.go, submitter/relayer/estimator.go
=> chore: disable tls in config

CHANGELOG.md, config/bitcoin.go
=> chore: change default max

CHANGELOG.md, e2etest/submitter_e2e_test.go, submitter/relayer/relayer.go
=> chore: submitter e2e for tx values bellow dust

CHANGELOG.md, btcstaking-tracker/atomicslasher/routines.go, btcstaking-tracker/atomicslasher/types.go, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, cmd/vigilante/cmd/reporter.go, config/config.go, e2etest/monitor_e2e_test.go, e2etest/reporter_e2e_test.go, e2etest/unbondingwatcher_e2e_test.go, metrics/btcstaking_tracker.go, metrics/reporter.go, reporter/reporter.go, reporter/utils.go, reporter/utils_test.go
Adds new metrics that indicate that censorship has happened. 
closes #272
=> chore: metrics for censorship detection

CHANGELOG.md, sample-vigilante.yml
Should we also include:
```
submitter:
insufficient_fee_margin
insufficient_feerate_margin
fee_increment_margin
```
=> chore: sync sample config

CHANGELOG.md, cmd/vigilante/cmd/config.go, cmd/vigilante/cmd/root.go, config/config.go, go.mod
=> chore: dump config command

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, metrics/btcstaking_tracker.go
Adds metrics for btc best block and babylon btc light client tip
=> chore: unbonding watcher block metrics

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, btcstaking-tracker/tracker.go, monitor/monitor.go, reporter/reporter.go, submitter/submitter.go
Reduces high log noise in unbonding watcher
=> chore: sew reduce logs

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, btcstaking-tracker/tracker.go, monitor/monitor.go, reporter/reporter.go, submitter/submitter.go
Reduces high log noise in unbonding watcher
=> chore: sew reduce logs (#303)

CHANGELOG.md, config/config.go, config/config_test.go, config/monitor.go, config/submitter.go
We need this in the `dump-cfg` cmd
=> fix: default config saving

CHANGELOG.md, config/config.go, config/config_test.go, config/monitor.go, config/submitter.go
We need this in the `dump-cfg` cmd
=> fix: default config saving (#315)

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go
=> fix: correctly increment page for stk hash query

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go
=> fix: correctly increment page for stk hash query (#359)

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, e2etest/unbondingwatcher_e2e_test.go
_VIG - Potential duplicate event processing due to overlapping block height_
=> chore: do not reprocess block heights (#369)

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go
closes https://github.com/babylonlabs-io/vigilante/issues/382
=> feat: adds reconnect mechanism for btc notifier

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go
closes https://github.com/babylonlabs-io/vigilante/issues/382
=> feat: adds reconnect mechanism for btc notifier (#399)

CHANGELOG.md, e2etest/slasher_e2e_test.go
adds e2e to test many slashing txns
closes #433
=> chore: many slashing transactions
