btcclient/client.go, btcclient/client_wallet.go, btcclient/query.go, btcstaking-tracker/atomicslasher/atomic_slasher.go, btcstaking-tracker/atomicslasher/babylon_adapter.go, btcstaking-tracker/btcslasher/bootstrapping_test.go, btcstaking-tracker/btcslasher/slasher.go, btcstaking-tracker/btcslasher/slasher_test.go, btcstaking-tracker/btcslasher/slasher_utils.go, btcstaking-tracker/tracker.go, cmd/vigilante/cmd/btcstaking_tracker.go, cmd/vigilante/cmd/monitor.go, cmd/vigilante/cmd/reporter.go, cmd/vigilante/cmd/submitter.go, config/common.go, e2etest/submitter_e2e_test.go, e2etest/test_manager.go, go.mod, go.sum, monitor/liveness_checker_test.go, monitor/query.go, reporter/reporter.go, reporter/utils.go, retrywrap/retry.go, retrywrap/retry_test.go, submitter/submitter.go
Replaces usage of `retry.do` from babylon with `avast/retry-go`
[References issue](https://github.com/babylonlabs-io/vigilante/issues/8)
=> chore(*): use proper retry

btcstaking-tracker/btcslasher/bootstrapping_test.go, btcstaking-tracker/btcslasher/slasher_test.go, e2etest/atomicslasher_e2e_test.go, e2etest/babylon_node_handler.go, e2etest/test_manager.go, e2etest/test_manager_btcstaking.go, go.mod, go.sum, tools/go.mod, tools/go.sum
Updates babylond version 
[References issue ](https://github.com/babylonlabs-io/vigilante/issues/33)
=> chore(*): update babylon version

btcstaking-tracker/btcslasher/bootstrapping_test.go, btcstaking-tracker/btcslasher/slasher.go, btcstaking-tracker/btcslasher/slasher_test.go, btcstaking-tracker/tracker.go, config/btcstaking_tracker.go
Limits the number of concurrent requests managed by a semaphore
[References issue](https://github.com/babylonchain/vigilante-private/issues/48)
=> chore(btcslasher): uses semaphore to limit btc node requests

e2etest/reporter_e2e_test.go, monitor/btcscanner/block_handler.go, monitor/btcscanner/btc_scanner.go, monitor/btcscanner/btc_scanner_test.go
Hygiene PR, unexport all fields in btcscanner
=> chore(btcscanner): unexport fields

Makefile, e2etest/atomicslasher_e2e_test.go, e2etest/container/container.go, e2etest/monitor_e2e_test.go, e2etest/reporter_e2e_test.go, e2etest/slasher_e2e_test.go, e2etest/submitter_e2e_test.go, e2etest/test_manager.go, e2etest/unbondingwatcher_e2e_test.go
Execute e2e tests in parallel.
Speed up from `15m` -> `3m`
=> chore(e2e): run e2e tests in parallel

Makefile, e2etest/container/container.go, e2etest/reporter_e2e_test.go, testutil/port.go
Sometimes due to parallel tests, we could end up with the same port allocated. In this PR I try to introduce a small timeout when testing port availability by opening it for a short time which should decrease the chance of collision.
Tested with no collision couple of times with:
```sh
go test -mod=readonly -failfast -timeout=15m -v $(PACKAGES_E2E) -count=30 --parallel 12 --tags=e2e
```
[References issue](https://github.com/babylonlabs-io/vigilante/issues/59)
=> chore(e2e): better port selection

btcclient/client_wallet.go, btcclient/interface.go, e2etest/reporter_e2e_test.go, e2etest/submitter_e2e_test.go, submitter/relayer/relayer.go, submitter/submitter.go, testutil/mocks/btcclient.go
Code cleanup
[References issue ](https://github.com/babylonchain/vigilante/issues/178)
=> chore(submitter): refactoring points 

config/dbconfig.go, config/monitor.go, config/submitter.go
Fixes db config meta fields to conform viper
=> fix(config): fix db config meta fields

config/dbconfig.go, config/monitor.go, config/submitter.go, e2etest/container/config.go, e2etest/container/container.go, e2etest/test_manager.go, testutil/version.go
=> chore(*): backport

btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, btcstaking-tracker/stakingeventwatcher/tracked_delegations.go, e2etest/test_manager_btcstaking.go, e2etest/unbondingwatcher_e2e_test.go
This PR introduces an end-to-end test to validate that when both a staking transaction and an unbonding transaction are included in the same block, the delegation correctly transitions to the "UNBONDED" status.
=> chore(e2e): e2e test for activating and unbonded in mempool

btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, btcstaking-tracker/stakingeventwatcher/tracked_delegations.go, e2etest/test_manager_btcstaking.go, e2etest/unbondingwatcher_e2e_test.go
backporting `24da0381465249aa7b55be682a66e32cdaddc81b`
=> chore(*): backport to v0.11.2

.github/workflows/changelog-reminder.yml, .github/workflows/ci.yml, .gitignore, .goreleaser.yml, CHANGELOG.md, Makefile
This PR
- sets up Go releaser for Babylon. Currently it only supports linux amd64. Other targets will be supported in the future. To test locally, run `make release-snapshot`
- moves changelog reminder out from the CI flow
=> ci: add goreleaser setup and move out changelog reminder

.goreleaser.yml, CHANGELOG.md, Makefile
=> chore(gorelaser): arm64 static build

CHANGELOG.md, cmd/vigilante/cmd/submitter.go, e2etest/monitor_e2e_test.go, e2etest/submitter_e2e_test.go, submitter/relayer/change_address_test.go, submitter/relayer/relayer.go, submitter/submitter.go, types/ckpt_info.go
Handles a case where there are no change outputs
=> fix(submitter): handle no change output

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, btcstaking-tracker/stakingeventwatcher/tracked_delegations.go
Limit go routines getting spawned and doing extra work.
=> fix(sew): limit go routine spawn for activating delegation

CHANGELOG.md, btcstaking-tracker/btcslasher/bootstrapping.go, btcstaking-tracker/btcslasher/bootstrapping_test.go, btcstaking-tracker/btcslasher/slasher_test.go, btcstaking-tracker/btcslasher/slasher_utils.go, btcstaking-tracker/stakingeventwatcher/expected_babylon_client.go, btcstaking-tracker/stakingeventwatcher/mock_babylon_client.go, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, e2etest/atomicslasher_e2e_test.go, e2etest/container/config.go, e2etest/slasher_e2e_test.go, e2etest/test_manager_btcstaking.go, e2etest/unbondingwatcher_e2e_test.go, go.mod, go.sum
Extends staking event watcher to be able to send whole stake spending tx as well as inclusion proof.
=> feat(sew): ADR-029 generalized unbonding and babylon v0.13.0

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, btcstaking-tracker/stakingeventwatcher/tracked_delegations.go
references [issue](https://github.com/babylonlabs-io/vigilante/issues/86)
=> chore(swe): prevent stale reads

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/expected_babylon_client.go, btcstaking-tracker/stakingeventwatcher/mock_babylon_client.go, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, btcstaking-tracker/tracker.go, e2etest/unbondingwatcher_e2e_test.go
Wait for the stacking transaction to be k-deep before submitting the inclusion proof
=> fix(swe): wait for stacking tx to be k-deep

.goreleaser.yml, CHANGELOG.md
=> chore: backport goreleaser

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, metrics/btcstaking_tracker.go
Adds more metrics for better visibility
=> chore(bstracker): add more metrics (#123)

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, btcstaking-tracker/stakingeventwatcher/tracked_delegations.go, metrics/btcstaking_tracker.go
This should solve a long lock wait time, which happens when fetching delegations into the tracker and trying to update a tracker
=> chore(sew): improvments to staking event tracker

CHANGELOG.md, submitter/relayer/relayer.go, submitter/submitter.go
resolve this issue: https://github.com/babylonlabs-io/vigilante/issues/137
=> fix: panic in SendCheckpointToBTC

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go
Adds rate limit to number of activation go routines to less the load on RPC
=> chore: add semaphore to rate limit activations

.github/workflows/changelog-reminder.yml, .github/workflows/ci.yml, .github/workflows/goreleaser.yml, .github/workflows/publish.yml
version: https://github.com/babylonlabs-io/.github/blob/main/CHANGELOG.md#0112
Includes a fix for docker builds triggered by external contributor PRs.
=> CI: Bump pipelines to latest versions

CHANGELOG.md, reporter/utils.go
Increase the default retry amount from default 5 which we have in bbn client reliable send msg to 60
=> chore: retry more when submitting headers

CHANGELOG.md, config/grpc.go, config/grpcweb.go, submitter/relayer/relayer.go
=> fix: resend tx panic (#154)

CHANGELOG.md, reporter/utils.go
Increase the default retry amount from default 5 which we have in bbn client reliable send msg to 60
=> chore: retry more when submitting headers (#155)

CHANGELOG.md, submitter/relayer/relayer.go
We forgot to update the time o the checkpoint.
closes #151 again
=> fix: resubmit interval (#160) [backport]

CHANGELOG.md, metrics/btcstaking_tracker.go
Our method executions aren't sub 1s, so we need to adjust
=> chore: better buckets for method latency 

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher_test.go, btcstaking-tracker/stakingeventwatcher/tracked_delegations.go, metrics/btcstaking_tracker.go
Adds 2 new metrics for bs tracker
closes #172
=> chore: metrics for bs tracker

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, btcstaking-tracker/stakingeventwatcher/tracked_delegations.go, e2etest/unbondingwatcher_e2e_test.go
We were returning nil, making the statement never true
=> fix: removing from metrics tracker

CHANGELOG.md, submitter/relayer/relayer.go
Regarding the comment: "Submitter will only re-attempt to submit the checkpoint once the
configured `PollingIntervalSeconds` has elapsed.", not relevant as rewards for checkpoint submitters will not be distributed in the near term.
closes #220, ref to BP2-021
=> chore: lax unecessary btc tx checks

CHANGELOG.md, btcstaking-tracker/atomicslasher/routines.go
often in e2e we see [err](https://github.com/babylonlabs-io/vigilante/actions/runs/13409769846/job/37457033675?pr=236):
```
goroutine 28015 [running]:
github.com/babylonlabs-io/vigilante/btcstaking-tracker/atomicslasher.(*AtomicSlasher).slashingTxTracker(0xc002e4ebe0)
/home/runner/work/vigilante/vigilante/btcstaking-tracker/atomicslasher/routines.go:89 +0x7a9
created by github.com/babylonlabs-io/vigilante/btcstaking-tracker/atomicslasher.(*AtomicSlasher).Start.func1 in goroutine 28053
/home/runner/work/vigilante/vigilante/btcstaking-tracker/atomicslasher/atomic_slasher.go:85 +0x89
FAIL	github.com/babylonlabs-io/vigilante/e2etest	197.720s
FAIL
```
=> fix: send on closed chan

CHANGELOG.md, testutil/port.go
we often have flaky tests due to mutex not properly working in the e2e for allocating port.
Trying to fix it with a file-based lock.
err that we often see:
```sh
API error (500): driver failed programming external connectivity on endpoint bitcoind-TestSlasher_SlashingUnbonding (5208fb0daff063a1ae7474082c19156de8b38fe74163adac195016b465db3f89): Error starting userland proxy: listen tcp4 0.0.0.0:35448: bind: address already in use
```
=> chore: use file based lock

CHANGELOG.md, sample-vigilante.yml
Also, seeing the sample-vigilante-docker.yml is out of sync
=> chore: Add fetch-evidence-interval to sample config

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go
We got an odd error in this [issue](https://github.com/babylonlabs-io/vigilante/issues/288). 
The only way we would try submitting unbonding txn without funding txns would be if `getFundingTxs` returned empty slice. We add additional checks and errors for this. 
Inspecting the txn `70647aec15bfd4689b1f1a630f55b5abdab9e03980ed139cd851873652f565ec` points out that it does have inputs, so the function should have returned a non nil slice.
=> chore: additional check for getFundingtx

CHANGELOG.md, Makefile, cmd/vigilante/cmd/root.go, cmd/vigilante/cmd/version.go, version/version.go
adds command `vigilante version`:
```
Version:       main
Git Commit:    8f37f70
Git Timestamp: 2025-03-29T14:45:14Z
```
=> chore: version cmd

CHANGELOG.md, config/btcstaking_tracker.go, config/common.go
https://github.com/golang/go/blob/644b984027d11d43881507a938b28ed9df3b3320/src/time/tick.go#L37
in time.ticker, if checks if time.Interval is less than or equal with 0.
but vigilante doesn't check it and if I set to 0, it throws error.
=> fix: Reject non-negative value and Zero for time Interval used by time.ticker

CHANGELOG.md, e2etest/bitcoind_node_setup.go, e2etest/container/container.go, e2etest/electrs_setup.go, e2etest/test_manager.go
As we still get conflicts on ports somehow 🤷, we introduce retries to start the container. 
```
test_manager.go:143: 
[539](https://github.com/babylonlabs-io/vigilante/actions/runs/14154681891/job/39652388908?pr=295#step:7:540)
Error Trace:	/home/runner/work/vigilante/vigilante/e2etest/test_manager.go:143
[540](https://github.com/babylonlabs-io/vigilante/actions/runs/14154681891/job/39652388908?pr=295#step:7:541)
/home/runner/work/vigilante/vigilante/e2etest/reporter_e2e_test.go:259
[541](https://github.com/babylonlabs-io/vigilante/actions/runs/14154681891/job/39652388908?pr=295#step:7:542)
Error:      	Received unexpected error:
[542](https://github.com/babylonlabs-io/vigilante/actions/runs/14154681891/job/39652388908?pr=295#step:7:543)
API error (500): driver failed programming external …
```
=> chore: tm retry container start

CHANGELOG.md, btcstaking-tracker/btcslasher/slasher_utils.go, btcstaking-tracker/btcslasher/slasher_utils_internal_test.go
We want to make sure to retry until slashing is done or slashing is not possible (both staking and unbonding txs are not slashable)
closes [334](https://github.com/babylonlabs-io/pm/issues/334)
=> feat: inf slash attempts

CHANGELOG.md, btcstaking-tracker/btcslasher/slasher_utils.go, btcstaking-tracker/btcslasher/slasher_utils_internal_test.go
We want to make sure to retry until slashing is done or slashing is not possible (both staking and unbonding txs are not slashable)
closes [334](https://github.com/babylonlabs-io/pm/issues/334)
=> feat: inf slash attempts (#328) [backport]

CHANGELOG.md, reporter/bootstrapping.go, reporter/reporter.go, reporter/utils.go, types/ckpt_cache.go
Make sure we don't have concurrent calls to bootstrap until we finish with async handling for the call to ProcessCheckpoints
=> chore: bootstrap only once

CHANGELOG.md, e2etest/reporter_e2e_test.go, reporter/expected_babylon_client.go, reporter/mock_babylon_client.go, reporter/utils.go, reporter/utils_test.go, retrywrap/retry.go
- https://github.com/babylonlabs-io/vigilante/issues/329
- https://github.com/babylonlabs-io/vigilante/issues/322
This PR resolves an issue where reporters repeatedly attempt to submit headers that have already been committed, resulting in prolonged retry cycles and unnecessary resource consumption.
This behavior occurred because submitHeaderMsgs() was designed to detect btclctypes.ErrForkStartWithKnownHeader using errors.Is(), but the error was often wrapped, causing the check to fail. In addition, the retry logic in both retrywrap.Do() and InsertHeaders() did not classify this error as expected, leading to redundant retries.
Replace InsertHeaders with ReliablySendMsg
Uses expectedErrors to explicitly classify
btclctypes.ErrForkStartWithKnownHeader as a known, non-fatal error.
Prevents …
=> fix: Prevent reporter retry loop on ErrForkStartWithKnownHeader (#330) [backport]

CHANGELOG.md, reporter/bootstrapping.go, reporter/reporter.go, reporter/utils.go, types/ckpt_cache.go
Make sure we don't have concurrent calls to bootstrap until we finish with async handling for the call to ProcessCheckpoints
=> chore: bootstrap only once (#327)

CHANGELOG.md, reporter/utils.go
We want to update the metrics even if some other reporter submitted checkpoints. Otherwise, we are getting false alarms (we don't like a lot of noise, we want a high signal-to-noise ratio).
=> chore: update reporter metric for checkpoints

CHANGELOG.md, reporter/utils.go
We want to update the metrics even if some other reporter submitted checkpoints. Otherwise, we are getting false alarms (we don't like a lot of noise, we want a high signal-to-noise ratio).
=> chore: update reporter metric for checkpoints (#340)

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go, e2etest/unbondingwatcher_e2e_test.go
Avoid processing block range in the border.
Reference to: VIG: Potential duplicate event processing due to overlapping block height ranges
=> chore: manage overlap block range

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go
34. Inefficient handling of failing events
=> chore: staking event watcher add retry

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go
References: VIG: Enforce monotonic block height processing on Vigilante
=> chore: enforce monotonic block height in unbonding watcher (#364)

CHANGELOG.md, btcstaking-tracker/stakingeventwatcher/stakingeventwatcher.go
Avoid processing block range in the border.
Reference to: VIG: Potential duplicate event processing due to overlapping block height ranges
=> chore: manage overlap block range (#362)

CHANGELOG.md, btcstaking-tracker/btcslasher/slasher.go
Seems that we no longer get race condition on the PK. This was making slashing of delegations of a FP sequential
=> fix: remove mutex on pk in slasher (#395) [backport]

CHANGELOG.md, submitter/relayer/relayer.go
This PR fixes a critical nil pointer panic that occurs in the submitter when attempting to resubmit checkpoints.
The submitter crashes with a nil pointer dereference when trying to access `ckptInfo.Tx2.Size` in calculateBumpedFee(). This happens because:
1. lastSubmittedCheckpoint is initialized as an empty `&types.CheckpointInfo{}` with nil Tx1 and Tx2 fields
2. When the first checkpoint resubmission is attempted, the code tries to access `Tx2.Size` without checking if Tx2 is nil
Added nil checks at the beginning of calculateBumpedFee() to validate that both ckptInfo and ckptInfo.Tx2 are not nil before accessing their fields.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x39bebec]
goroutine 90 …
```
=> fix: nil check in calculateBumpedFee
